name: Deploy frontend tp github pages
on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v4
      
      - name: setup node.js runtime
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: install monorepo folder dependencies
        run: |
          cd frontend
          npm ci
      
      - name: compile static astro application
        run: |
          cd frontend
          npm run build

      - name: package and upload web artifacts
        uses: actions/upload-pages-artifact@v3
        with: 
          path: ./frontend/dist
        
      - name: deploy to GitHub pages
        id: deployment
        uses: actions/configure-pages@v5