name: Deploy frontend tp github pages
on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v4
      
      - name: setup node.js runtime
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: install monorepo folder dependencies
        run: |
          cd frontend
          npm install
      
      - name: compile static astro application
        run: |
          cd frontend
          npx astro build --root .

      - name: package and upload web artifacts
        uses: actions/upload-pages-artifact@v3
        with: 
          path: ./frontend/dist
  deploy:
    needs: build
    permissions: 
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: publish live to github pages
        id: deployment
        uses: actions/deploy-pages@v4